services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  celery:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: celery_beat
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    command: celery -A app.celery_app.celery_app beat --loglevel=info

  flower:
    build:
      context: .
      dockerfile: Dockerfile.celery
    container_name: flower
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
    command: celery -A app.celery_app.celery_app flower --loglevel=info
    ports:
      - "5555:5555"

  db:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: smart_booking
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

volumes:
  postgres_data: