"""Add is_blocked to users

Revision ID: 4bff605a255a
Revises: 50f01b5214af
Create Date: 2024-12-22 23:57:41.800706

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4bff605a255a"
down_revision: Union[str, None] = "50f01b5214af"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("is_blocked", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_blocked")
    # ### end Alembic commands ###
