"""Update access_log model

Revision ID: 762eedacb2b0
Revises: 4bff605a255a
Create Date: 2025-01-08 22:25:32.969467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762eedacb2b0'
down_revision: Union[str, None] = '4bff605a255a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_logs', sa.Column('command', sa.String(), nullable=False))
    op.add_column('access_logs', sa.Column('response_status', sa.String(), nullable=False))
    op.add_column('access_logs', sa.Column('response_message', sa.String(), nullable=True))
    op.alter_column('access_logs', 'access_code_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('access_logs', 'access_code_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('access_logs', 'response_message')
    op.drop_column('access_logs', 'response_status')
    op.drop_column('access_logs', 'command')
    # ### end Alembic commands ###
